### ISSUE TITLE
Implement Programs page design

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#830]
The design for the programs page is near completion via issue #804.
![early learning programs v6](https://user-images.githubusercontent.com/5550969/28249439-f2439b46-6a12-11e7-97d8-a70db6ea9d83.png)

Things to do for this page:
- [x] Create a new URL because it is currently /families
- [x] Point /families to this new page in case the old URL is out in the world
- [x] Get updated content from partners (use placeholder content below)
- [ ] Build birthday checker feature (see issue #829)
- [x] Receive approval/get feedback on apple graphic (https://github.com/smartchicago/chicago-early-learning/issues/804#issuecomment-315620784)

Current placeholder content:
## Look What We Can Do!
Through Chicago Early Learning, all of our families—no matter their needs—will be able to find and secure a quality early learning program.

“Every child in every neighborhood deserves a quality education and that must begin in their earliest years.” - Chicago Mayor Rahm Emanuel

## What early learning program should your child(ren) be enrolling in?
Enter a birthdate. The result will reflect what you should enroll in Fall 2017.

[Month]	[Date]		[Year]
[Submit Birthday]

## Infants (Ages Birth - 2)
These programs may also be referred to as Early Head Start, Prevention Initiative, or Early Intervention.

### Who do they serve?
Children aged birth to three years old from qualifying families

### What do they provide?
Educational and social development activities.
Programs may include free health services (medical, dental, mental health), nutritious meals, as well as parent education and training.

## Preschool (Ages 3 - 4)
Preschool programs may be referred to as Head Start or Preschool for All

### Who do they serve?
Three to five year old children from qualifying families

### What do they provide?
Educational and social development activities that promote school readiness.
Either a half-day or a full-day of instruction
Programs may include free health services (medical, dental, mental health), nutritious meals, as well as parent education and training.

## Kindergarten (Age 5)
[Placeholder text]

## Types of Programs
The early education programs at the City of Chicago are available in a number of settings:

### Chicago Public Schools (CPS) Programs
Age Group: 3 and 4
Many CPS elementary schools offer early learning programs as a part of their services.

### Community Based Programs
Age group: Birth to 5
Neighborhood locations provide early childhood education and infant and toddler care. Hours vary by site.

_Home Visiting Care is also available for qualifying families, for children between the ages of birth to 3. Visiting coaches provide early care and consulting in the family’s home to qualifying families._

#### What does “Quality Rating” (QRIS) mean?
Quality Rating indicates the quality of a site based on the Excelerate Illinois system. Excelerate Illinois is the new quality rating and improvement system for Illinois. It has been designed to rate the quality of early learning programs and to set a research based standard for early learning and development providers. There are tiered Circles of Quality in Excelerate and the higher the awarded tier, the more the program has made meaningful improvements that better the child for school and life. More information about Excelerate can be found at ExcelerateIllinois.com.

#### What does “Accreditation” mean?
Accreditation means that a program has met high standards of excellence determined by a national organization such as the National Association for the Education of Young Children (NAEYC), National Early Childhood Program Accreditation (NEPCA), or the Council on Accreditation (COA). Programs that receive national accreditation have demonstrated quality in areas such as teaching, curriculum, learning assessments, health, community relationships, physical environment, and management. To learn more about accreditation of early learning programs, click on one of the following links:

To learn more about accreditation of early learning programs, click on one of the following links:

National Association for the Education of Young Children 
National Early Childhood Program Accreditation 
Council on Accreditation  

## Choosing the Right Program
[Placeholder graphic that requires review]

## Other Local Activities and Resources
[Placeholder text]

## Kudos from our family members!
[Placeholder text]

**Comment by theandrewbriggs** [comment]
@smarziano @amynicole @jenmakes What's the intent for the function of the age calculator? I'm imagining just a scroll-to event on submit?

**Comment by theandrewbriggs** [comment]
Also, all - Styling dropdowns is one of those things that's almost never worth it and almost always bad, so two design suggestions for that age calculator: Either use default dropdown/select elements, or have a manual entry for birth date. I think the latter is the better choice from a usability standpoint?

**Comment by smarziano** [comment]
@theandrewbriggs I agree about having a manual entry for birth date. I imagine a scroll-to section might not be enough to tell parents that their child is ready for that program. I was imagining it would actually show a phrase like "Wow! Your child is ready for preschool programs this Fall! Learn more" and the "Learn more" might scroll to the proper section.

**Comment by smarziano** [comment]
Updates for this page:
- [ ] Add venn diagram graphic from #804 
- [ ] Utilize this photo for the Local Activities section:
![cb fave 1](https://user-images.githubusercontent.com/5550969/28587168-d75e0e44-713b-11e7-9c4c-de10c9b1f0e2.jpg)
- [ ] Add this photo for the infants block:
![chicagocommons4](https://user-images.githubusercontent.com/5550969/28587208-f33ecf68-713b-11e7-8eaa-3208eb3430cc.jpg)
- [ ] Add this photo for the preschool block:
![marycrane5](https://user-images.githubusercontent.com/5550969/28587265-24290f1c-713c-11e7-95a9-f99cb33df629.jpg)
- [ ] Add a spot for one testimonial with placeholder text as seen in the design above

**Comment by smarziano** [comment]
Based on the current site on staging, here are high priority and lower priority changes that need to made to this page. 

## High priority
- [ ] Tagline “Look what WE can do!” styling is missing
- [ ] Submit birthday block is missing confetti asset
- [ ] Birthday check block seems too thin… should be 470 px tall
- [ ] Quote is missing styling
- [ ] “What early learning…” text should be 24 px with 32 px line height
- [ ] “Who do they serve” and “what do they provide” should be 18px 
- [ ] QRIS & Accreditation headers should be 18px tall, 26px line height

## Lower priority
- [ ] More padding needed below hero 
- [ ] CPS & Community-based text does not line up
- [ ] Local activities and resource photo is not cropped properly (adjust or change photo)

**Comment by smarziano** [comment]
Here is updated content for this page. 

# Early Learning Programs

## Look What We Can Do!
Chicago Early Learning is bringing our city together to ensure that all of our families in need are able to find and enroll in a quality early learning opportunity.

“Every child in every neighborhood deserves a quality education and that must begin in their earliest years.” - Chicago Mayor Rahm Emanuel

## What early learning program is right for your child?
Enter your child’s birthdate to learn more about programs available to your family. 

[Month]	[Date]		[Year]
[Submit Birthday]

## Infants (Ages Birth - 2)
These programs may also be referred to as Early Head Start, Prevention Initiative, or Early Intervention.

### Who do they serve?
Children aged birth to 3 years old from qualifying families

### What do they provide?
- Educational and social development activities.
- Programs may include free health services (medical, dental, mental health), nutritious meals, as well as parent education and training.

[Find sites]

## Preschool (Ages 3 & 4)
Preschool programs may be referred to as Head Start or Preschool for All

### Who do they serve?
3- and 4-year-old children from qualifying families

### What do they provide?
- Educational and social development activities that promote school readiness.
- Either a half-day or a full-day of instruction
- Programs may include free health services (medical, dental, mental health), nutritious meals, as well as parent education and training.

[Find sites]

Kindergarten (Age 5)
Children who are 5 years old by September 1st of the current school year should enroll in kindergarten at a CPS preschool. Visit the CPS website to enroll a child in kindergarten.

[Learn more]

## Types of Programs
The early education programs at the City of Chicago are available in a number of settings:

### Chicago Public Schools (CPS) Programs
Age Group: 3 and 4
Many CPS elementary schools offer early learning programs as a part of their services.

### Community-Based Programs
Age group: Birth to 5
Neighborhood locations provide early childhood education and infant and toddler care. Hours vary by site.

_Home Visiting Care is also available for qualifying families, for children between the ages of birth to 3. Visiting coaches provide early care and consulting in the family’s home to qualifying families._

## Choosing the Right Program

### Quality Ratings 
Quality ratings for Chicago Early Learning programs, and programs across Illinois and the country, offer families more insight before they make final choices about a program for their child. 

#### What does “Quality Rating” (QRIS) mean?
Quality Ratings are assessments of early learning programs used by Excelerate Illinois to help families understand program quality and help providers prioritize improvements. Excelerate Illinois, the state’s rating and improvement system, sets a research-based standard for early learning and development providers, reflected in its tiered Circles of Quality. The higher the tier, the more the program has made meaningful improvements that better the child for school and life. Reviewing a potential preschool program’s rating in Excelerate’s Circles of Quality can help Illinois families make a more informed decision for their child. More information can be found at ExcelerateIllinois.com.

#### What does “Accreditation” mean?
Accreditation is another way of measuring and understanding early learning program quality; accredited status means that a program has met high standards of excellence determined by a national organization such as the National Association for the Education of Young Children (NAEYC), National Early Childhood Program Accreditation (NEPCA), or the Council on Accreditation (COA). These quality standards measure areas such as  teaching, curriculum, learning assessments, health, community relationships, physical environment, and management. To learn more about accreditation of early learning programs and how such standards can help guide families searching for early learning programs, click on one of the following links:

- National Association for the Education of Young Children 
- National Early Childhood Program Accreditation 
- Council on Accreditation  

[Apple venn diagram]

## Other Local Activities and Resources
See our Resources page [link] to learn more about programs for young children throughout the city that are not part of Chicago Early Learning. 

## Kudos from our family members!
[Placeholder text]

**Comment by smarziano** [comment]
There were a lot of improvements made with last night's commits (f0769f3...ddffa0f), and I went ahead and checked off the items from our last comment that were completed (https://github.com/smartchicago/chicago-early-learning/issues/830#issuecomment-318423528). Please see above.

Here are some other final tasks that should be completed:
## Desktop
### Higher priority
- [ ] Add apple venn diagram asset
- [ ] Infants block "Learn more" button is white font and yellow background and hard to read. Can we change the colors for additional contrast? (@amynicole)
- [ ] Update "Learn more" buttons on both Infant and Preschool blocks to "Find Sites"
- [ ] Change "Infants" headline to "Infants and Toddlers"
- [ ] Change sizing of CPS and Community-based assets. They appear too big. (@amynicole)

### Lower priority
- [ ] Check mayor quote font styling (@amynicole)
- [ ] Check "What early learning program should your child(ren) be enrolling in?" font styling (@amynicole)
- [ ] Change "About Early Learning Programs" to just "Programs" (because I think it's clear enough)

## Mobile
- [ ] Text of "Submit Birthday" button is cut off
- [ ] Photo of "Other Local Activities and Resources" does not fit in block space (too short)

**Comment by amynicole** [comment]
@theandrewbriggs are you able to resize the assets in code?

**Comment by amynicole** [comment]
Mayor font styling should be:
Montserrat Regular
24px tall
32 px line height
Yellow line to the side

Font styling for "– CHICAGO MAYOR RAHM EMANUEL"
Montserrat Medium
13 px tall

**Comment by smarziano** [comment]
There are a few unchecked items in these comments:
https://github.com/smartchicago/chicago-early-learning/issues/830#issuecomment-318794920
https://github.com/smartchicago/chicago-early-learning/issues/830#issuecomment-318423528

Also, can we get the tagline "Look what WE can do!" on one line?

**Comment by smarziano** [comment]
Another task for this page is to implement the alternative mobile designs for the venn diagram:
![iphone 7](https://user-images.githubusercontent.com/5550969/28764077-633fb6ce-7588-11e7-9085-fe0700fafcf2.png)
