### ISSUE TITLE
Design tweaks to /how-to-apply page

### ISSUE THREAD

**Issue by smarziano** [smartchicago/chicago-early-learning#879]
Here are design tweaks to our /how-to-apply page:

- [ ] Increase padding between "Are you ready..." headline and text
- [ ] Lines are missing between steps (#850)
- [ ] Add grey line separating "Follow these steps" and Step 1
<img width="882" alt="screen shot 2017-08-16 at 3 45 47 pm" src="https://user-images.githubusercontent.com/5550969/29384511-fe5ccfca-8299-11e7-820c-e92fb768db3c.png">

- [ ] Shorten "View Family Resources" button to about 340px wide
- [ ] "FAQ page" hyperlink in first block should be orange and italics
- [ ] Increase line height on subheadlines to 30px
- [ ] Phone number link in "Go to school" should be orange and italics
- [ ] Increase padding within blue tiles at bottom of page to match design in issue #833 
<img width="694" alt="screen shot 2017-08-16 at 3 49 25 pm" src="https://user-images.githubusercontent.com/5550969/29384659-7f06359e-829a-11e7-9430-dea3c5687c69.png">

- [ ] Update header image (issue #849)

**Comment by theandrewbriggs** [comment]
All of these are on production except for the new header image and the step lines. Lines between steps are not doable without significant reconstruction of this page (relates to #850)

**Comment by smarziano** [comment]
@theandrewbriggs Regarding your comment, I will see if there is another photo that works better. If not, I really like this one and we can keep it. 

As for the lines between steps, we still need to add the new SVGs that include the numbers since we do not have a line between each step.

**Comment by amynicole** [comment]
I exported the assets with the numbers to help with this! Andrew, let me know if you have any issue with them.
